// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAVwtk59fl6teX3WrIzraGfA58YaJew1M',
    appId: '1:788625825745:web:44b8e62eac17ba33950af0',
    messagingSenderId: '788625825745',
    projectId: 'laptopharbor-9c98e',
    authDomain: 'laptopharbor-9c98e.firebaseapp.com',
    storageBucket: 'laptopharbor-9c98e.firebasestorage.app',
    measurementId: 'G-GFGFK143NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA05C7XHYzmof5vqY0djGKurGp_8SJrgvw',
    appId: '1:788625825745:android:eb935d508c673a66950af0',
    messagingSenderId: '788625825745',
    projectId: 'laptopharbor-9c98e',
    storageBucket: 'laptopharbor-9c98e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxy5V-gdiz0remXsMaGwqoPeg335NCdMY',
    appId: '1:788625825745:ios:f37c9061a935e045950af0',
    messagingSenderId: '788625825745',
    projectId: 'laptopharbor-9c98e',
    storageBucket: 'laptopharbor-9c98e.firebasestorage.app',
    iosBundleId: 'com.example.laptopharbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxy5V-gdiz0remXsMaGwqoPeg335NCdMY',
    appId: '1:788625825745:ios:f37c9061a935e045950af0',
    messagingSenderId: '788625825745',
    projectId: 'laptopharbor-9c98e',
    storageBucket: 'laptopharbor-9c98e.firebasestorage.app',
    iosBundleId: 'com.example.laptopharbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAVwtk59fl6teX3WrIzraGfA58YaJew1M',
    appId: '1:788625825745:web:1ff0632147f0e48c950af0',
    messagingSenderId: '788625825745',
    projectId: 'laptopharbor-9c98e',
    authDomain: 'laptopharbor-9c98e.firebaseapp.com',
    storageBucket: 'laptopharbor-9c98e.firebasestorage.app',
    measurementId: 'G-YKDR63JVP1',
  );

}